package com.ex.tiredman.libs;

public enum OBJECT {
		OBJECT_MOONS_HEAD,
		OBJECT_MOONS_BODY,
		OBJECT_MOONS_FOOT,
		OBJECT_MOONS_EYE_LEFT,
		OBJECT_MOONS_EYE_RIGHT,
		OBJECT_MOONS_EAR_LEFT,
		OBJECT_MOONS_EAR_RIGHT,
		OBJECT_THING_WASH,
		OBJECT_THING_WASH_AFTER,
		OBJECT_THING_WASHLINE,
		OBJECT_THING_WASHBOX
}
